name: Benchmark (PR)

on:
  push:
    branches: [test-me-*]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  benchmark_cpu:
    name: CPU Pytest benchmark
    runs-on: ubuntu-latest

    steps:
    - uses: kornia/workflows/.github/actions/env@v1.5.3
      with:
        fetch-depth: 25 # this is to make sure we obtain the target base commit

    - name: Setup benchmarks
      run: |
        echo "HEAD_JSON=$(mktemp)" >> $GITHUB_ENV
        echo "BASE_JSON=$(mktemp)" >> $GITHUB_ENV
        echo "PR_COMMENT=$(mktemp)" >>  $GITHUB_ENV
        echo "RUN_BENCHMARK='pytest -vvv --benchmark-json '" >>  $GITHUB_ENV

    - name: Install benchmark requirements
      run: pip install -r requirements/requirements-benchmarks.txt

    - name: Run benchmarks
      run: |
        cd benchmarks/
        git checkout ${{ github.event.pull_request.base.sha }}
        ${{ env.RUN_BENCHMARK }} ${{ env.BASE_JSON }}
        git checkout ${{ github.sha }}
        ${{ env.RUN_BENCHMARK }} ${{ env.HEAD_JSON }}

    - name: Comment results
      uses: apbard/pytest-benchmark-commenter@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        benchmark-file: ${{ env.HEAD_JSON }}
        comparison-benchmark-file: ${{ env.BASE_JSON }}
        benchmark-metrics: 'name,max,mean,ops'
        comparison-benchmark-metric: 'ops'
        comparison-higher-is-better: true
        comparison-threshold: 5
        benchmark-title: 'Result of CPU Benchmark Tests'
